SRC = corewar.c check_arg.c parse_player.c
LIB = ../../libft/libft.a
INC = -I../../includes
LUB = -llibft.a
NAME = corewar


all :
	#rm -f exe.cor
	#rm -f asm
	gcc -g $(SRC) $(LIB) $(INC) -o $(NAME)
	#hexdump -C exe.cor
